### ISSUE TITLE
Significant Lag in on_event_trade_update in Fast Market

### ISSUE THREAD

**Issue by igkoh** [hbdmapi/hbdm_Python#8]
Order book and trade are important in market making decisions..
Trade data is updated in async def on_event_trade_update as

_main.py : quant.start() ->
quant.py : loop_run_forever -> 
events.py : callback -> 
strategy.py : async on_event_trade_update_

If the **market changes very fast, async**  **on_event_trade_update may lag significantly**.
**How can I detect significant time lag in trade**?
Guess is  using the same logic as received orderbook timestamp exceed, and modified as

async def on_ticker(self, *args, **kwargs):

        _ts_diff = int(time.time()*1000) - self.last_trade_timestamp
        if ts_diff > self.trade_invalid_seconds * 1000:
		            logger.warn("received trade timestamp exceed:", self.strategy, self.symbol, ts_diff, caller=self)
            return_

Fast price changes are very important in cryptocurrency.  How can I **avoid significant time delay in trade data?**

Best regards,
Ingyu

**Comment by foonsun** [comment]
@igkoh   If the market changes very fast, async  on_event_trade_update may lag significantly.
How can I detect significant time lag in trade?
 
 A: The trade data is pushed once there is a trade filled. It will not be pushed if there is no trade filled.You can use the same logic as received orderbook timestamp exceed,however,it is only for your reference because the trade will not be pushed if there is no trade filled.
      
 
Fast price changes are very important in cryptocurrency.  How can I avoid significant time delay in trade data?

A: If significant time delay in trade data occurs, You’d better refer to both orderbook data and trade data.If the gap is too big,you have to handle it properly.
